// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "alc/view/layout"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"space-y-6\"><h1 class=\"text-2xl font-bold\">Administración</h1><form class=\"space-y-1\" method=\"post\" action=\"/admin/equipos\" enctype=\"multipart/form-data\" autocomplete=\"off\" hx-post=\"/admin/equipos\" hx-target=\"#equipos-target\" hx-on::after-request=\"this.reset();\"><h2 class=\"text-xl font-bold\">Subir equipos</h2><div id=\"equipos-target\"></div><div><input type=\"file\" accept=\".csv\" name=\"EquiposData\"></div><button type=\"submit\" class=\"px-3 py-1 bg-gray-300 border border-black\">Subir</button></form><form class=\"space-y-1\" method=\"post\" action=\"/admin/clientes\" enctype=\"multipart/form-data\" autocomplete=\"off\" hx-post=\"/admin/clientes\" hx-target=\"#clientes-target\" hx-on::after-request=\"this.reset();\"><h2 class=\"text-xl font-bold\">Subir usuarios</h2><div id=\"clientes-target\"></div><div><input type=\"file\" accept=\".csv\" name=\"ClientesData\"></div><button type=\"submit\" class=\"px-3 py-1 bg-gray-300 border border-black\">Subir</button></form><div><h2 class=\"text-xl font-bold\">Descargar constancias</h2><a href=\"/admin/constancias\" class=\"px-3 py-1 bg-gray-300 border border-black\">Descargar</a></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.BasePage("Administrador").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
