services:
  webserver:
    image: "elbromasmc/alc-rimac"
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - ../pdf:/pdf
  db:
    restart: unless-stopped

