// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "alc/view/layout"

func SignupShow() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"flex justify-center items-center py-12 min-h-dvh bg-sky-100 sm:px-4\"><section class=\"px-9 py-16 w-full bg-white sm:max-w-xl sm:rounded-3xl\"><div class=\"flex gap-4 items-center\"><h2 class=\"font-semibold text-4xl\">Regístrate!</h2><img id=\"login-indicator\" class=\"htmx-indicator w-9\" src=\"/static/img/bars.svg\"></div><div id=\"error-message\" class=\"min-h-6\"></div><form class=\"space-y-6\" action=\"/admin/signup\" method=\"post\" hx-post=\"/admin/signup\" hx-target=\"#error-message\" hx-target-error=\"#error-message\" hx-indicator=\"#login-indicator\" hx-on::after-request=\"this.reset();\"><div><label class=\"block text-lg\" for=\"name\">Nombre:</label> <input id=\"name\" class=\"block p-2 w-full border rounded-lg border-slate-500\" type=\"text\" name=\"name\" required></div><div><label class=\"block text-lg\" for=\"email\">Correo:</label> <input id=\"email\" class=\"block p-2 w-full border rounded-lg border-slate-500\" type=\"email\" name=\"email\" required></div><div><label class=\"block text-lg\" for=\"password\">Contraseña:</label> <input id=\"password\" class=\"block p-2 w-full border rounded-lg border-slate-500\" type=\"password\" name=\"password\" required></div><div><button class=\"w-full mt-3 p-2 border bg-azure border-azure rounded-3xl font-semibold text-chalky\" type=\"submit\">Registrarse</button></div></form></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Registro").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
